# name: Deploy Jekyll site to GitHub Pages

# on:
#   push:
#     branches:
      - main  # uncomment everything above

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Updated to version 3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Make sure this matches your environment

      - name: Install dependencies
        run: bundle install

      - name: Setup Node.js (for building CSS)
        uses: actions/setup-node@v3  # Set up the Node.js environment
        with:
          node-version: '16' # Use Node.js 16 or update to '20' if needed

      - name: Install npm dependencies
        run: npm install  # Install dependencies from package.json

      - name: Build CSS
        run: npm run build:css  # Add your CSS build step here

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to version 4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Ensure this is your correct build directory